// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzajxjyachcavzmbddjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWp4anlhY2hjYXZ6bWJkZGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjYyMTYsImV4cCI6MjA3MDk0MjIxNn0.dNhejYR1HWGDuEMHONtA1pz0o1JCVjFOq6_C-TyQyUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});